name: jalali_table_calendar
description: Tabel Calendar , Calendar DatePacker , Datepicker and Date Convertor For Persian Date(Jalali/Shamsi date) with holidays.
version: 1.1.2
homepage: https://github.com/Azare77/jalali_table_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  jiffy: ^6.3.1
  persian_number_utility: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
